import Foundation

let thisFileUrl = URL(fileURLWithPath: #filePath)
let rootDirectoryUrl = thisFileUrl.deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
let geminiApiKey = getEnvironmentVariable("GEMINI_API_KEY")!
let remoteOpenAPIUrl = URL(string: "https://generativelanguage.googleapis.com/$discovery/OPENAPI3_0?version=v1beta&key=\(geminiApiKey)")!
let originalOpenAPIUrl = rootDirectoryUrl.appendingPathComponent("assets/original.json")
let outputOpenAPIUrl = rootDirectoryUrl.appendingPathComponent("assets/openapi.json")

func saveOriginalOpenAPI() throws -> String {
    let originalOpenAPI = try! String(contentsOf: remoteOpenAPIUrl, encoding: .utf8)
    try originalOpenAPI.write(to: originalOpenAPIUrl, atomically: true, encoding: .utf8)
    print("Saved original OpenAPI to \(originalOpenAPIUrl)")
    return originalOpenAPI
}

@main
struct PrepareMain {

    func runAll() throws {
        let originalOpenAPI = try saveOriginalOpenAPI()

        let newOpenAPI = originalOpenAPI.replacingOccurrences(
            of: ###"""
                      "Part": {
                        "type": "object",
                        "description": "A datatype containing media that is part of a multi-part `Content` message.\n\nA `Part` consists of data which has an associated datatype. A `Part` can only\ncontain one of the accepted types in `Part.data`.\n\nA `Part` must have a fixed IANA MIME type identifying the type and subtype\nof the media if the `inline_data` field is filled with raw bytes.",
                        "properties": {
                          "fileData": {
                            "description": "URI based data.",
                            "allOf": [
                              {
                                "$ref": "#/components/schemas/FileData"
                              }
                            ]
                          },
                          "functionCall": {
                            "description": "A predicted `FunctionCall` returned from the model that contains\na string representing the `FunctionDeclaration.name` with the\narguments and their values.",
                            "allOf": [
                              {
                                "$ref": "#/components/schemas/FunctionCall"
                              }
                            ]
                          },
                          "thought": {
                            "type": "boolean",
                            "description": "Optional. Indicates if the part is thought from the model."
                          },
                          "executableCode": {
                            "description": "Code generated by the model that is meant to be executed.",
                            "allOf": [
                              {
                                "$ref": "#/components/schemas/ExecutableCode"
                              }
                            ]
                          },
                          "inlineData": {
                            "description": "Inline media bytes.",
                            "allOf": [
                              {
                                "$ref": "#/components/schemas/Blob"
                              }
                            ]
                          },
                          "videoMetadata": {
                            "allOf": [
                              {
                                "$ref": "#/components/schemas/VideoMetadata"
                              }
                            ],
                            "description": "Optional. Video metadata. The metadata should only be specified while the video\ndata is presented in inline_data or file_data."
                          },
                          "codeExecutionResult": {
                            "description": "Result of executing the `ExecutableCode`.",
                            "allOf": [
                              {
                                "$ref": "#/components/schemas/CodeExecutionResult"
                              }
                            ]
                          },
                          "text": {
                            "type": "string",
                            "description": "Inline text."
                          },
                          "thoughtSignature": {
                            "description": "Optional. An opaque signature for the thought so it can be reused in subsequent\nrequests.",
                            "type": "string",
                            "format": "byte"
                          },
                          "functionResponse": {
                            "description": "The result output of a `FunctionCall` that contains a string\nrepresenting the `FunctionDeclaration.name` and a structured JSON\nobject containing any output from the function is used as context to\nthe model.",
                            "allOf": [
                              {
                                "$ref": "#/components/schemas/FunctionResponse"
                              }
                            ]
                          }
                        }
                      },
                """###,
            with: ###"""
                      "TextPart": {
                        "type": "object",
                        "properties": {
                          "text": {
                            "type": "string",
                            "description": "Inline text."
                          }
                        },
                        "required": [
                          "text"
                        ]
                      },
                      "InlineDataPart": {
                        "type": "object",
                        "properties": {
                          "inlineData": {
                            "description": "Inline media bytes.",
                            "$ref": "#/components/schemas/Blob"
                          }
                        },
                        "required": [
                          "inlineData"
                        ]
                      },
                      "FunctionCallPart": {
                        "type": "object",
                        "properties": {
                          "functionCall": {
                            "description": "A predicted `FunctionCall` returned from the model that contains\na string representing the `FunctionDeclaration.name` with the\narguments and their values.",
                            "$ref": "#/components/schemas/FunctionCall"
                          }
                        },
                        "required": [
                          "functionCall"
                        ]
                      },
                      "FunctionResponsePart": {
                        "type": "object",
                        "properties": {
                          "functionResponse": {
                            "description": "The result output of a `FunctionCall` that contains a string\nrepresenting the `FunctionDeclaration.name` and a structured JSON\nobject containing any output from the function is used as context to\nthe model.",
                            "$ref": "#/components/schemas/FunctionResponse"
                          }
                        },
                        "required": [
                          "functionResponse"
                        ]
                      },
                      "FileDataPart": {
                        "type": "object",
                        "properties": {
                          "fileData": {
                            "description": "URI based data.",
                            "$ref": "#/components/schemas/FileData"
                          }
                        },
                        "required": [
                          "fileData"
                        ]
                      },
                      "ExecutableCodePart": {
                        "type": "object",
                        "properties": {
                          "executableCode": {
                            "description": "Code generated by the model that is meant to be executed.",
                            "$ref": "#/components/schemas/ExecutableCode"
                          }
                        },
                        "required": [
                          "executableCode"
                        ]
                      },
                      "CodeExecutionResultPart": {
                        "type": "object",
                        "properties": {
                          "codeExecutionResult": {
                            "description": "Result of executing the `ExecutableCode`.",
                            "$ref": "#/components/schemas/CodeExecutionResult"
                          }
                        },
                        "required": [
                          "codeExecutionResult"
                        ]
                      },
                      "VideoMetadataPart": {
                        "type": "object",
                        "properties": {
                          "videoMetadata": {
                            "description": "Video metadata.",
                            "$ref": "#/components/schemas/VideoMetadata"
                          }
                        },
                        "required": [
                          "videoMetadata"
                        ]
                      },
                      "ThoughtSignaturePart": {
                        "type": "object",
                        "properties": {
                          "thoughtSignature": {
                            "type": "string",
                            "format": "byte",
                            "description": "Optional. An opaque signature for the thought so it can be reused in subsequent\nrequests."
                          }
                        }
                      },
                      "Part": {
                        "type": "object",
                        "description": "A datatype containing media that is part of a multi-part `Content` message.\n\nA `Part` consists of data which has an associated datatype. A `Part` can only\ncontain one of the accepted types in `Part.data`.\n\nA `Part` must have a fixed IANA MIME type identifying the type and subtype\nof the media if the `inline_data` field is filled with raw bytes.",
                        "oneOf": [
                          {
                            "$ref": "#/components/schemas/TextPart"
                          },
                          {
                            "$ref": "#/components/schemas/InlineDataPart"
                          },
                          {
                            "$ref": "#/components/schemas/FunctionCallPart"
                          },
                          {
                            "$ref": "#/components/schemas/FunctionResponsePart"
                          },
                          {
                            "$ref": "#/components/schemas/FileDataPart"
                          },
                          {
                            "$ref": "#/components/schemas/ExecutableCodePart"
                          },
                          {
                            "$ref": "#/components/schemas/CodeExecutionResultPart"
                          },
                          {
                            "$ref": "#/components/schemas/ThoughtSignaturePart"
                          },
                          {
                            "$ref": "#/components/schemas/VideoMetadataPart"
                          }
                        ]
                      },
                """###
        )

        // Save original OpenAPI to output file
        assert(newOpenAPI != originalOpenAPI)
        try! newOpenAPI.write(to: outputOpenAPIUrl, atomically: true, encoding: .utf8)

        // Generate Swift code from OpenAPI
        try runCommand("make generate-openapi")
    }

    static func main() throws {
        try saveOriginalOpenAPI()
    }
}
